name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run job.py
        env:
          SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}
        run: python job.py
      - name: Write file
        run: echo "contenu du fichier" > output.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mon-artefact
          path: output.txt
      - run: echo "🍏 This job's status is ${{ job.status }}."