name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
        env:
          SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
      - run: python -m unittest -v
      - run: sshpass -p "$SSH_PASSWORD" scp |